version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run lint
          command: npm run lint:report
      - run:
          name: Run tests
          command: npm run test:coverage
      - store_test_results:
          path: test-results.xml
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.5.1
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Pack package
          command: npm pack
      - run:
          name: Publish package
          command: npm publish --dry-run
      - store_artifacts:
          path: ~/repo/my-awesome-package-1.1.0.tgz
          destination: package/release.tgz
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
      - store_artifacts:
          path: ~/repo/docs
          destination: docs

workflows:
  test-deploy:
    jobs:
      - test:
          context: dev
      - deploy:
          context: dev
          requires:
            - test